# This is a basic workflow to help you get started with Actions
name: Pruebas Unitarias y Merge a Dev
on:
  push:
    branches: [DMAG-*]

jobs:
  back:
    name: Pruebas backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v2
    - name: Configuracion de entorno Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Instalacion de librerias y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r flaskr/requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: |
        python -m unittest discover tests/
    - name: Validar resultado con errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
    - name: Validar resultado sin errores
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Todas las pruebas fueron exitosas
      run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"
  front:
      name: Pruebas Frontend
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with: 
          node-version: '14'    
      - name: Install dependencies
        run: |
          cd front-end/tutorial-canciones/
          npm install
      - name: Correr pruebas angular
        run: |
          cd front-end/tutorial-canciones/
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: Validar resultado con errores
        if: ${{ failure() }}
        env:
          MENSAJE_ERROR: Una o varias pruebas fallaron
        run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
      - name: Validar resultado sin errores
        if: ${{ success() }}
        env:
          MENSAJE_EXITO: Todas las pruebas fueron exitosas
        run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"  
  merge-branch:
    name: Automerge
    needs: [back, front]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge rama actual -> dev
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: dev
          github_token: ${{ github.token }}
